language: node_js
osx: osx
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
  - npm install uglify-js -g

script:
  - docker exec -it emscripten make
