language: minimal
os: linux
dist: trusty

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - touch Makefile
  - docker exec -it emscripten make docs/tour.js
  - make
