language: node_js
os: linux
dist: trusty
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
  - npm install uglify-js -g
  - touch Makefile

script:
  - docker exec -it emscripten make docs/tour.js
  - make
